import Head from 'next/head'
import AboutOurMission from '../sections/about-our-mission'

export default function Home() {
  return (
    <>
      <Head>
        <title>Prysmatic about us page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutOurMission />
    </>
  )
}
