import {useRef, useEffect} from 'react'
import Head from 'next/head'
import {useRouter} from 'next/router'
import AboutOurMission from '../sections/about-our-mission'
import AboutOurVision from '../sections/about-our-vision'
import AboutMeetTeam from '../sections/about-meet-team'
import PrysmTeamWork from '../sections/prysm-teamwork'

export default function About() {
  const missionRef = useRef(null)
  const visionRef = useRef(null)
  const teamRef = useRef(null)

  const router = useRouter()

  const currentSection = router.query['section'] || null

  useEffect(() => {
    setTimeout(() => {
      switch (currentSection) {
        case 'mission':
          missionRef.current?.scrollIntoView({behavior: 'smooth'})
          break
        case 'vision':
          visionRef.current?.scrollIntoView({behavior: 'smooth'})
          break
        case 'team':
          teamRef.current?.scrollIntoView({behavior: 'smooth'})
          break
        default:
          null
      }
    }, 10)
  }, [router, currentSection])

  return (
    <>
      <Head>
        <title>Prysmatic about us page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutOurMission ref={missionRef} />

      <AboutOurVision ref={visionRef} />

      <section className="py-6 md:py-16 bg-body-gradient dark:bg-none overflow-x-hidden overflow-y-auto">
        <div className="container">
          <AboutMeetTeam ref={teamRef} />

          <PrysmTeamWork isNested />
        </div>
      </section>
    </>
  )
}
