import {useRef, useEffect} from 'react'
import Head from 'next/head'
import {useRouter} from 'next/router'
import CareersWorkWithUs from '../sections/careers-work-with-us'

export default function Careers() {
  const careersWorkWithUsRef = useRef(null)

  const router = useRouter()

  const currentSection = router.query['section'] || null

  useEffect(() => {
    setTimeout(() => {
      switch (currentSection) {
        case 'work-with-us':
          careersWorkWithUsRef.current?.scrollIntoView({behavior: 'smooth'})
          break
        default:
          null
      }
    }, 10)
  }, [router, currentSection])

  return (
    <>
      <Head>
        <title>Prysmatic сareers page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CareersWorkWithUs ref={careersWorkWithUsRef} />
    </>
  )
}
