import { useEffect } from 'react'
import Head from 'next/head'
import IndexHero from '../components/index-hero'

export default function Home() {
  const bodyClasses = [
    'bg-gradient-to-b',
    'from-gradient-start',
    'via-gradient-via',
    'to-gradient-via',
    'text-semi-white',
  ]
  useEffect(() => {
    document.body.classList.add(...bodyClasses)
  })

  return (
    <>
      <Head>
        <title>Prysmatic landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexHero />
    </>
  )
}
